### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by baio** [ng-holistic/platform#25]
- [ ] Move all examples to https://stackblitz.com/
- [ ] Create FAQ section (How do I) with links to examples
- [ ] Style documentation site
